services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: moviedb-postgres
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: